name: Commit lint (legacy)

on:
  pull_request:
    branches: [master]
    paths:
      - ./packages/library-legacy/

jobs:
  web3-commit-lint:
    name: Validate commit message
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need to fetch the base SHA so that it can be compared with the head SHA.
          fetch-depth: 0

      - name: Install package manager
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check that commit message conforms to Semantic Release format
        if: ${{ github.event_name == 'pull_request' }}
        run: bash commitlint.sh ./packages/library-legacy/
        env:
          COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
