name: Pull requests

on:
  pull_request:

env:
  # Among other things, opts out of Turborepo telemetry
  # See https://consoledonottrack.com/
  DO_NOT_TRACK: '1'
  SSH_KEY: ${{ secrets.SSH_KEY }}
  # Enables Turborepo Remote Caching.
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
  id-token: write
  contents: read

jobs:
  # Needed for grouping check-web3 strategies into one check for mergify
  all-web3-checks:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - run: echo "Done"

  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 'current'
          - 'lts/*'

    name: Build & Test on Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install package manager
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get Test Validator Latest Release
        id: get-test-validator-version
        run: |
          echo "version=$(./scripts/get-latest-validator-release-version.sh)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Test Validator
        id: cache-test-validator
        uses: actions/cache@v3
        with:
          path: .solana
          key: ${{ runner.os }}-test-validator-${{ steps.get-test-validator-version.outputs.version }}

      - name: Install Test Validator
        if: steps.cache-test-validator.outputs.cache-hit != 'true'
        run: scripts/setup-test-validator.sh

      - name: Is the validator running before the tests?
        run: ps aux | grep validator

      - name: Build & Test
        run: pnpm build --concurrency=100%

      - name: Is the validator still running after the tests?
        run: ps aux | grep validator

      - name: Breakpoint if tests failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: buffalojoec, steveluscher

      - name: Upload Experimental library build artifacts
        if: matrix.node == 'current'
        uses: actions/upload-artifact@v3
        with:
          name: library-dist
          path: |
            ./packages/library/dist/
            ./packages/library/package.json
